Gradient Boost

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn import metrics
from sklearn.model_selection import train_test_split

I have one of three datasets that is designed to predict a binary yes or no, so that is the only dataset I will work with this week. The variable "DEP_DEL15" is 1 is a flight was delayed greater than 15 minutes at departure and 0 if it was not.

In [2]:
#Import 2nd Dataset, 2019 Flight Delay Info

delays_2019 = pd.read_csv(r"C:\Users\lemrd\Downloads\OMDS\Mod B\Sem 2\Data\2019_Delay_Data\full_data_flightdelay.csv")

delays_2019.head()

,MONTH,DAY_OF_WEEK,DEP_DEL15,DEP_TIME_BLK,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,...,PLANE_AGE,DEPARTING_AIRPORT,LATITUDE,LONGITUDE,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND
0,1,7,0,0800-0859,2,1,25,143,Southwest Airlines Co.,13056,...,8,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
1,1,7,0,0700-0759,7,1,29,191,Delta Air Lines Inc.,13056,...,3,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
2,1,7,0,0600-0659,7,1,27,199,Delta Air Lines Inc.,13056,...,18,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
3,1,7,0,0600-0659,9,1,27,180,Delta Air Lines Inc.,13056,...,2,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
4,1,7,0,0001-0559,7,1,10,182,Spirit Air Lines,13056,...,1,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91

In [3]:
#The target variable for this dataset is "DEP_DEL15" it is a binary 1 if the flight was delayed more than 15 minutes in its departure delay else 0
delays_2019.drop(["DEP_TIME_BLK","DEPARTING_AIRPORT", "PREVIOUS_AIRPORT", "CARRIER_NAME"], axis=1, inplace=True)

target_2019 = delays_2019["DEP_DEL15"]
variables_2019 = delays_2019.drop(["DEP_DEL15"], axis = 1)

In [4]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(variables_2019, target_2019, random_state=42)

I am going to use Precision as the scoring metric since this is predicting significantly delayed flights. Most flights are not delayed so I want to minimize false positives.

There are many more than 10,000 samples so I will be using HistGradientBoostingClassifier. There are over 6 million flights recorded in this dataset.

In [8]:
#Optimize Histogram-based Gradient Boosting Classification Tree
hgbc = HistGradientBoostingClassifier()
param_grid = {
    "max_depth" : [15,20,50],
    "max_leaf_nodes" : [21,26,31,36,41],
    "min_samples_leaf" : [1,5,10,20,50],
    "learning_rate" : [.05,.1,.15,.25,.5,.75]
}

hgbc_cv = RandomizedSearchCV(hgbc, param_distributions=param_grid, n_iter=30, scoring = "precision").fit(X_train,y_train)

print(hgbc_cv.best_params_)

{'min_samples_leaf': 20, 'max_leaf_nodes': 21, 'max_depth': 50, 'learning_rate': 0.05}

In [9]:
hgbc = HistGradientBoostingClassifier(min_samples_leaf=20,max_leaf_nodes=21,max_depth=50, learning_rate=.05).fit(X_train,y_train)

train_pred = hgbc.predict(X_train)
test_pred = hgbc.predict(X_test)

train_prec = metrics.precision_score(y_train,train_pred)
test_prec = metrics.precision_score(y_test,test_pred)

print(f"The precision on the training data was {train_prec:.4f} and on the test data was {test_prec:.4f}")

The precision on the training data was 0.7016 and on the test data was 0.7056

About 70% of the flights the model predicted to be significantly delayed in both the training and test sets were actually significantly delayed. That is just about the same as the 75% on training and 72% on the test data from Random Forest Regression. There might be room for improvement if I take longer to check more sets of parameters though ~70% might also just be the reasonable precision cap for this data.

In [2]:
#Import smallest dataset to be appended to other datasets
#This dataset is measure of a few simple totals that work as a representation of the logistical complexity of each airport
domestic_data_2024 = pd.read_csv(r"C:\Users\lemrd\Downloads\OMDS\Mod B\Sem 2\Data\T100_Domestic_Market_and_Segment_Data_8942359590531559889.csv")
domestic_data_2024.drop(["year", "enplanements", "arrivals", "OBJECTID"], axis=1, inplace=True) #Redundant with other columns
domestic_data_2024.head()

  origin  passengers  departures  freight  mail
0    01A          17           5        0     0
1    05A           1           1        0     0
2    06A          55          67      139     0
3    09A          43          15        0     0
4    1B1          32           7        0     0

In [3]:
#Import 2015 Flight Delay Data
#Columns 7,8 needed dtype specified directly as infer failed

flights_2015 = pd.read_csv(r"C:\Users\lemrd\Downloads\OMDS\Mod B\Sem 2\Data\2015_Delay_Data\flights.csv", dtype={"DESTINATION_AIRPORT":str, "ORIGIN_AIRPORT":str})

flights_2015.fillna({"AIR_SYSTEM_DELAY":0,"SECURITY_DELAY":0,"AIRLINE_DELAY":0,"LATE_AIRCRAFT_DELAY":0,"WEATHER_DELAY":0}, inplace=True)
flights_2015.head()

   YEAR  MONTH  DAY  ...  AIRLINE_DELAY LATE_AIRCRAFT_DELAY  WEATHER_DELAY
0  2015      1    1  ...            0.0                 0.0            0.0
1  2015      1    1  ...            0.0                 0.0            0.0
2  2015      1    1  ...            0.0                 0.0            0.0
3  2015      1    1  ...            0.0                 0.0            0.0
4  2015      1    1  ...            0.0                 0.0            0.0

[5 rows x 31 columns]

In [4]:
#Append airport logistics numbers to the 2015 Flight Delay Dataset
domestic_data_2024.rename({"origin" : "ORIGIN_AIRPORT"}, inplace=True, axis=1)
flight_2015_extended = pd.merge(flights_2015, domestic_data_2024, how='left', on="ORIGIN_AIRPORT")
flight_2015_extended.head()

   YEAR  MONTH  DAY  ...  departures       freight        mail
0  2015      1    1  ...     71765.0  3.116064e+09  95095127.0
1  2015      1    1  ...    206637.0  8.440161e+08  47992961.0
2  2015      1    1  ...    138571.0  2.182348e+08   8795256.0
3  2015      1    1  ...    206637.0  8.440161e+08  47992961.0
4  2015      1    1  ...    191107.0  3.490318e+08  14452644.0

[5 rows x 35 columns]

In [5]:
#Drop Non-Numeric Columns
flight_2015_delay_vars = flight_2015_extended.drop(["AIRLINE", "TAIL_NUMBER", "ORIGIN_AIRPORT", "DESTINATION_AIRPORT", "CANCELLATION_REASON"], axis=1)
flight_2015_delay_vars.dropna(axis=0, inplace=True)

target = flight_2015_delay_vars["ARRIVAL_DELAY"]
variables = flight_2015_delay_vars.drop("ARRIVAL_DELAY", axis=1)

#Train test split
X_train, X_test, y_train, y_test = train_test_split(variables, target, random_state=42)

In [6]:
#Optimize Histogram-based Gradient Boosting Classification Tree
hgbr = HistGradientBoostingRegressor()
param_grid = {
    "max_depth" : [15,20,30,40,50],
    "max_leaf_nodes" : [21,26,31,36,41],
    "min_samples_leaf" : [1,5,10,20,50],
    "learning_rate" : [.05,.1,.15,.25,.5,.75]
}

hgbr_cv = RandomizedSearchCV(hgbr, param_distributions=param_grid, n_iter=30, scoring = "neg_root_mean_squared_error").fit(X_train,y_train)

print(hgbr_cv.best_params_)

{'min_samples_leaf': 1, 'max_leaf_nodes': 41, 'max_depth': 40, 'learning_rate': 0.25}

In [9]:
hgbr = HistGradientBoostingRegressor(min_samples_leaf = 1, max_leaf_nodes = 41, max_depth = 40, learning_rate = 0.25).fit(X_train,y_train)

train_pred = hgbr.predict(X_train)
test_pred = hgbr.predict(X_test)

train_rmse = metrics.root_mean_squared_error(y_train,train_pred)
test_rmse = metrics.root_mean_squared_error(y_test,test_pred)

print(f"The RMSE on the training data was {train_rmse:.4f} minutes and on the test data was {test_rmse:.4f} minutes")

The RMSE on the training data was 3.4356 minutes and on the test data was 4.0209 minutes

In [10]:
#Import Delays and Causes Dataset

delay_causes = pd.read_csv(r"C:\Users\lemrd\Downloads\OMDS\Mod B\Sem 2\Data\Flight_Delay_and_Causes_Data\Flight_delay.csv")
#Remove the few duplicate datapoints
delay_causes.drop_duplicates(keep="first", inplace=True)
#Drop columns with no information (all values are the same)
delay_causes.drop(["Cancelled","Diverted","CancellationCode"],axis=1, inplace=True)
#Fix long delays to break out of 24 hour time to show the real delay length
data_to_shift = delay_causes[delay_causes["ArrTime"] < (delay_causes["CRSArrTime"] - 100)].index
delay_causes.loc[data_to_shift,"ArrTime"] = delay_causes.loc[data_to_shift,"ArrTime"] + 2400
                           
delay_causes.head()

   DayOfWeek        Date  DepTime  ...  NASDelay  SecurityDelay LateAircraftDelay
0          4  03-01-2019     1829  ...         0              0                32
1          4  03-01-2019     1937  ...         0              0                47
2          4  03-01-2019     1644  ...         0              0                72
3          4  03-01-2019     1452  ...         0              0                12
4          4  03-01-2019     1323  ...         0              0                16

[5 rows x 26 columns]

In [11]:
#Append Logistics Dataset
domestic_data_2024.rename({"ORIGIN_AIRPORT" : "Origin"}, inplace=True, axis=1)
delay_causes_extended = pd.merge(delay_causes, domestic_data_2024, how='left', on="Origin")
delay_causes_extended.head()

   DayOfWeek        Date  DepTime  ...  departures      freight     mail
0          4  03-01-2019     1829  ...     60772.0  842478043.0  84741.0
1          4  03-01-2019     1937  ...     60772.0  842478043.0  84741.0
2          4  03-01-2019     1644  ...     60772.0  842478043.0  84741.0
3          4  03-01-2019     1452  ...     60772.0  842478043.0  84741.0
4          4  03-01-2019     1323  ...     60772.0  842478043.0  84741.0

[5 rows x 30 columns]

In [12]:
#Drop non-numeric columns
num_delay_causes = delay_causes_extended.drop(["Date", "UniqueCarrier", "Airline", "TailNum", "Origin", "Org_Airport", "Dest", "Dest_Airport"], axis = 1)
#Drop missing data
num_delay_causes.dropna(axis=0, inplace=True)

target_delay = num_delay_causes["ArrDelay"]
variables_delay = num_delay_causes.drop(["ArrDelay"], axis = 1)

#Train Test Split
X_train, X_test, y_train, y_test = train_test_split(variables_delay, target_delay, random_state=42, test_size=.1)

In [13]:
#Optimize Histogram-based Gradient Boosting Classification Tree
hgbr = HistGradientBoostingRegressor()
param_grid = {
    "max_depth" : [15,20,30,40,50],
    "max_leaf_nodes" : [21,26,31,36,41],
    "min_samples_leaf" : [1,5,10,20,50],
    "learning_rate" : [.05,.1,.15,.25,.5,.75]
}

hgbr_cv = RandomizedSearchCV(hgbr, param_distributions=param_grid, n_iter=30, scoring = "neg_root_mean_squared_error").fit(X_train,y_train)

print(hgbr_cv.best_params_)

{'min_samples_leaf': 1, 'max_leaf_nodes': 41, 'max_depth': 20, 'learning_rate': 0.25}

In [14]:
hgbr = HistGradientBoostingRegressor(min_samples_leaf = 1, max_leaf_nodes = 41, max_depth = 20, learning_rate = 0.25).fit(X_train,y_train)

train_pred = hgbr.predict(X_train)
test_pred = hgbr.predict(X_test)

train_rmse = metrics.root_mean_squared_error(y_train,train_pred)
test_rmse = metrics.root_mean_squared_error(y_test,test_pred)

print(f"The RMSE on the training data was {train_rmse:.4f} minutes and on the test data was {test_rmse:.4f} minutes")

The RMSE on the training data was 3.3667 minutes and on the test data was 3.9235 minutes